// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpYVyc8UQnjUqHXRQ5VSO2RoSyAKjRc5M',
    appId: '1:561890103119:web:5da09400abc42a3388ff3a',
    messagingSenderId: '561890103119',
    projectId: 'badymonitoring',
    authDomain: 'badymonitoring.firebaseapp.com',
    storageBucket: 'badymonitoring.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVxMz8yM-0JfgHSBDeekMqWW60OmL2Rvg',
    appId: '1:561890103119:android:f0aaa8382869466788ff3a',
    messagingSenderId: '561890103119',
    projectId: 'badymonitoring',
    storageBucket: 'badymonitoring.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB46em2DZQ0DauL1uWKxjJpa8uXojkR7H8',
    appId: '1:561890103119:ios:9c51311990a3f7bd88ff3a',
    messagingSenderId: '561890103119',
    projectId: 'badymonitoring',
    storageBucket: 'badymonitoring.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB46em2DZQ0DauL1uWKxjJpa8uXojkR7H8',
    appId: '1:561890103119:ios:9c51311990a3f7bd88ff3a',
    messagingSenderId: '561890103119',
    projectId: 'badymonitoring',
    storageBucket: 'badymonitoring.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpYVyc8UQnjUqHXRQ5VSO2RoSyAKjRc5M',
    appId: '1:561890103119:web:7de485dc925f581f88ff3a',
    messagingSenderId: '561890103119',
    projectId: 'badymonitoring',
    authDomain: 'badymonitoring.firebaseapp.com',
    storageBucket: 'badymonitoring.appspot.com',
  );
}
